version: '3'
services:
  api:
    build: .
    command: npm --prefix api start
    ports:
      - "3002:3002"
  frontend:
    build: .
    command: npm --prefix frontend-next run dev
    ports:
      - "3000:3000"
